<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Bharath" failures="1" tests="4" name="Test" time="0.064" errors="0" timestamp="2025-01-13T09:17:10 IST">
  <testcase classname="com.framework.testngConcepts.TestNGTests" name="TestCase1" time="0.008">
    <failure type="java.lang.AssertionError" message="Test Case 1 Failed">
      <![CDATA[java.lang.AssertionError: Test Case 1 Failed
at com.framework.testngConcepts.TestNGTests.TestCase1(TestNGTests.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TestCase1 -->
  <testcase classname="com.framework.testngConcepts.TestNGTests" name="TestCase2" time="0.001"/>
  <testcase classname="com.framework.testngConcepts.TestNGTests" name="TestCase3" time="0.003"/>
  <testcase classname="com.framework.testngConcepts.TestNGTests" name="TestCase3" time="0.001"/>
</testsuite> <!-- Test -->
